name: Build

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ update-data ]

jobs:
  main:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'Update') || startsWith(github.event.head_commit.message, 'Fix') || contains(github.event_name, 'repository_dispatch')

    steps:
    - uses: actions/checkout@v2
    - name: Checkout data repo
      uses: actions/checkout@v2
      with:
        repository: ShinyGroup/SCTranslationData
        path: scdata
    - name: Move data files
      run: cp -r scdata/data/ ./
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build data
      run: yarn deploy_action
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        repo: biuuu/ShinyColors
        target_branch: gh-pages
        build_dir: dist
      env:
        GH_PAT: ${{ secrets.COLORS_PAT }}
